apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: doks-ci-cd
spec:
  template:
    spec:
      containers:
        - image: 665986443982.dkr.ecr.ap-northeast-1.amazonaws.com/k8s-skaffold/chen-template