on: 
  push:
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
